### ISSUE TITLE
float/double support

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#151]
First,  I like jou language very much, it is a good language...
I download windows version and I want to make a "math.jou" for jou language (Maybe can be put in stdlib? "stdlib/math.jou") beacause lots of language have "math" lib, such as python, c++, c
But when I start writing "fabs" function, compiler gives me an error:
![image](https://user-images.githubusercontent.com/71159641/215311062-26a18f67-7e54-48f4-a6a6-cb4c6dd7ffc5.png)
Source code:
#### math.jou
```python
# This is a math lib for jou...?

def abs(n: int) -> int:
    if (n < 0):
        n *= -1
    return n

def fabs(n: float) -> float:
    if (n < 0):
        n *= -1
    return n
```
#### test.jou
```
# This is a test for math.jou
from "./math.jou" import fabs
from "stdlib/io.jou" import printf

def main() -> int:
    printf("%d", fabs(11))
    return 0
```
![image](https://user-images.githubusercontent.com/71159641/215311112-f39080a4-6e44-493a-b9ed-8af3b0e51bd5.png)
... Hope add float/double support
Or is there another way?

**Comment by Akuli** [comment]
I will eventually add float/double support, unless someone else contributes it first :)

As with most other features, this needs a couple small changes in almost all parts of the compiler. I now realize that I haven't documented very well how everything works, but the README at least gives you some kind of idea and explains how to tell the compiler to display a lot of internal stuff for you to see.

To get started implementing this, I would read `jou_compiler.h` and add whatever is needed into it (e.g. two new members `TYPE_FLOAT` and `TYPE_DOUBLE` into `enum TypeKind`). This will cause a few compiler errors in different parts of the compiler, because many places use `switch(type->kind) { ... }` and now need to handle the newly added values. Fix those errors.

Next I would make a file that contains something super simple, e.g. this:

```
from "stdlib/io.jou" import printf

def main() -> int:
    x: double = 12
    printf("%f\n", x)
    return 0
```

The first line `x: double = 12` should do an implicit cast from `int` to `double`. The `12.34` syntax should IMO be added later in a separate PR, because it could be a bit difficult to make the tokenizer understand it as something else than integers and a dot operator. Implicit conversions are easier to get to work.

Then it's a matter of running `make && jou --verbose asd.jou` (where `asd.jou` is the above file) and fixing errors until it works :)

If you can do some of this and submit a partially done PR, that will help a lot with me getting this done! You can commit the Jou file used in developing to `tests/should_succeed/`.

**Comment by littlewhitecloud** [comment]
I thought adding a wiki to briefly explain how variable types are implemented would be helpful for adding new types...
I tried add new types but I can only add a little piece...
And when I run the makefile It outputs error(The "Makefile" file's syntax doesn't support for Windows?)
![image](https://user-images.githubusercontent.com/71159641/215393341-d4b1f728-6168-43a1-86a8-1901fc1a95a6.png)
##### 'which' is not an internal or external command, nor is it a runnable program
##### Does which a command in Linux?
##### '/clang' is not an internal or external command, nor is it a runnable program
##### But my clang really exsit...
![image](https://user-images.githubusercontent.com/71159641/215393510-76821c18-7a98-4e62-a9f2-47278b0c77d4.png)
So how can compile jou on Windows? (My computer doesn't support WSL...)

**Comment by Akuli** [comment]
There is now very basic support for doubles. I make more issues about individual things that don't work. Maybe try fixing some of those :)

**Comment by Akuli** [comment]
Doubles work pretty well now, and there are individual issues for things that don't work.
