### ISSUE TITLE
littlewhitecloud's advices for jou syntax

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#152]
#### 1
I have look at the examples/primes.jou and I noticed the for loop.
I think the for loop requires "(" and ")" to make the for loop more read able
```python
from "stdlib/io.jou" import printf

def is_prime(n: int) -> bool:
    if n < 2:
        return False

    for (divisor = 2; divisor < n; divisor++): #here add "(" ")"
        if n % divisor == 0:
            return False
    return True

def main() -> int:
    for (n = 0; n < 10; n++): #here add "(" ")"
        if is_prime(n):
            printf("%d\n", n)
    return 0
```

**Comment by littlewhitecloud** [comment]
2
I hope the arguments can support this syntax:
#### [typename] [variable]
```python
def is_prime(int n) -> bool: # here changed
    if n < 2:
        return False
    for (divisor = 2; divisor < n; divisor++): #here add "(" ")"
        if n % divisor == 0:
            return False
    return True
```
Because I often use C/C++ coding......
```c
bool isprime(int n) { // typename variable
	if n < 2:
		return false
	// and more
}
```
This is just a suggest...

**Comment by Akuli** [comment]
Thanks for sharing your thoughts :)

Suggestion 1 would be inconsistent with `if` and `while`: they don't have parentheses in Jou or Python, but they have parentheses in C.

Suggestion 2: I don't want to add two ways to do the same thing (it would only be confusing), so I would delete the `variable: typename` syntax as well. But then `variable: typename = value` (e.g. `x: int = 'a'`) is inconsistent with how arguments work, and should also be changed to `int x = a`. This isn't great because `int x = a` is difficult to distinguish from `x = a` when parsing, and I want Jou to be super simple to parse.

**Comment by littlewhitecloud** [comment]
okay, thx for your reply
