### ISSUE TITLE
No installer for Mac/Linux

### ISSUE THREAD

**Issue by Moosems** [Akuli/jou#381]

**Comment by Akuli** [comment]
Linux doesn't really need an installer, because downloading something from github and running `make` is a very typical way to install a program on linux. IMO anything else would just feel weird to a linux user.

On a mac, Jou wouldn't work even if you got it to compile. I will keep this issue open as a reminder for me to fix this. I will have to at least use something else than `/proc/self/exe` to locate the `stdlib` folder.

**Comment by Moosems** [comment]
Duplicate of #158

**Comment by Akuli** [comment]
Maybe. If it turns out I want to work on Jou again at some point, mac support would be useful because more people could try Jou.

**Comment by Moosems** [comment]
Now it's just a letter of knowing the builtin functions and types and having docs for them.

**Comment by Akuli** [comment]
This is now duplicate with #518.
