### ISSUE TITLE
Replace the full path to 'Jou'?

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#506]
Before:
```console
D:\jou-main\jou-main\jou.exe: missing Jou file name (try "D:\jou-main\jou-main\jou.exe --help")
```
After:
```console
Jou: missing Jou file name (try "D:\jou-main\jou-main\jou.exe --help")
```

**Comment by Akuli** [comment]
This could be confusing if someone has two installations of jou.

How are you running jou? Jou uses `argv[0]` for these messages, and usually `argv[0]` is set to a shorter string, something like `"jou.exe"` (Windows) or `"./jou"` (MacOS and Linux).

**Comment by littlewhitecloud** [comment]
![image](https://github.com/Akuli/jou/assets/71159641/8723cc26-cdbf-4309-a55c-b971c833db2f)
It seems that the argv[0] didn't set to "./jou".

**Comment by Akuli** [comment]
Here's what it's supposed to look like:

![screenshot-1713091673](https://github.com/Akuli/jou/assets/18505570/0b6d3e66-df96-4433-9f25-4073bb1a0285)

Apparently this is a windows thing: https://stackoverflow.com/questions/7941536/windows-vs-linux-gcc-argv0-value

Using `argv[0]` to refer to "this program" is a standard thing to do in C, and almost all other programs do it, so changing it could be a bad idea. That said, I can't think of anything that would go wrong practically if we just use `"jou"` instead of `argv[0]`. Even if someone has two jous installed, there are other ways to check which jou is being used.

**Comment by littlewhitecloud** [comment]
Ok. Sorry to interrupt.

**Comment by Akuli** [comment]
No problem, it was a good question and I didn't know `argv[0]` is the full path on Windows :)
